#!/usr/bin/with-contenv bash

# create a config file for ld which points to our mounted nvidia driver directory in `/usr/local/nvidia`
# https://blog.sourced.tech/post/cuda_ldconfig/

echo "/usr/local/nvidia/lib" > /etc/ld.so.conf.d/cuda.conf

# https://forums.plex.tv/t/hardware-transcoding-stopped-working-gentoo-linux-solved/719595/29
echo "/usr/local/nvidia/lib" >> /usr/lib/plexmediaserver/etc/ld-musl-x86_64.path

ldconfig